# Generated by Django 3.2.5 on 2021-08-03 11:57

from django.db import migrations, models
import django.db.models.deletion
import stats.models


class Migration(migrations.Migration):
    """
    This migration may fail if the unicity constraints are violated in the database. You may have to manually correct
    these issues first.
    """

    dependencies = [
        ('stats', '0002_teammate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.game', validators=[stats.models.restrict_amount]),
        ),
        migrations.AddConstraint(
            model_name='playerstat',
            constraint=models.UniqueConstraint(fields=('game', 'pseudo'), name='no_duplicate_players'),
        ),
        migrations.AddConstraint(
            model_name='playerstat',
            constraint=models.UniqueConstraint(fields=('game', 'pokemon', 'is_opponent'), name='no_duplicate_pokemons_in_team'),
        ),
    ]
